#ifndef DEFS_H_INCLUDED
#define DEFS_H_INCLUDED

#define FIELD_SIZE 8
#define INITIAL_MINE_COUNT 6
#define MINE_SYMBOL '*'
#define EMPTY_POSITION ' '
#define VISITED_POSITION ' '
#define INITIAL_SYMBOL_FIELD_VISIBLE '#'


#endif // DEFS_H_INCLUDED